import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Navigation } from "@/components/navigation";
import { getCommonDictionary } from "@/translations/common/common-dictionary";
import { notFound } from "next/navigation";
import { LanguageSwitcher } from "@/components/language-switcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}>) {
  const { lang } = await params;

  const commonDictionary = await getCommonDictionary(
    lang === "pl" ? "pl" : "en"
  );

  console.log("lang", lang);
  return (
    <html lang={lang}>
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased dark w-full h-full`}
      >
        <div className="flex w-full justify-center">
          <Navigation commonDictionary={commonDictionary} />
        </div>
        {children}
        <LanguageSwitcher lang={lang} />
      </body>
    </html>
  );
}
